name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' # Удалите эту строку, если хотите опубликовать на pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Добавление ваших ресурсов (assets)
  assets:
    - assets/photo/  # Путь к папке с изображениями
